// Reads every GLB in assets/models and writes js/house/models.js with each model's
// true bounding box (node transforms applied). Run after adding/removing models:
//   node tools/build-models.mjs
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';

const dir = new URL('../assets/models/', import.meta.url);
const mul = (a, b) => {
  const r = new Array(16).fill(0);
  for (let i = 0; i < 4; i++) for (let j = 0; j < 4; j++) for (let k = 0; k < 4; k++) r[j * 4 + i] += a[k * 4 + i] * b[j * 4 + k];
  return r;
};
const trs = (n) => {
  if (n.matrix) return n.matrix;
  const [x, y, z, w] = n.rotation || [0, 0, 0, 1];
  const [sx, sy, sz] = n.scale || [1, 1, 1];
  const [tx, ty, tz] = n.translation || [0, 0, 0];
  return [
    (1 - 2 * (y * y + z * z)) * sx, 2 * (x * y + z * w) * sx, 2 * (x * z - y * w) * sx, 0,
    2 * (x * y - z * w) * sy, (1 - 2 * (x * x + z * z)) * sy, 2 * (y * z + x * w) * sy, 0,
    2 * (x * z + y * w) * sz, 2 * (y * z - x * w) * sz, (1 - 2 * (x * x + y * y)) * sz, 0,
    tx, ty, tz, 1,
  ];
};
const apply = (m, p) => [0, 1, 2].map((i) => m[i] * p[0] + m[4 + i] * p[1] + m[8 + i] * p[2] + m[12 + i]);
const r3 = (v) => Math.round(v * 1000) / 1000;

const out = {};
for (const f of readdirSync(dir).filter((f) => f.endsWith('.glb')).sort()) {
  const b = readFileSync(new URL(f, dir));
  const j = JSON.parse(b.subarray(20, 20 + b.readUInt32LE(12)).toString());
  const min = [Infinity, Infinity, Infinity];
  const max = [-Infinity, -Infinity, -Infinity];
  const walk = (ni, M) => {
    const n = j.nodes[ni];
    const W = mul(M, trs(n));
    if (n.mesh != null)
      for (const p of j.meshes[n.mesh].primitives) {
        const a = j.accessors[p.attributes.POSITION];
        for (const cx of [a.min[0], a.max[0]])
          for (const cy of [a.min[1], a.max[1]])
            for (const cz of [a.min[2], a.max[2]]) {
              const q = apply(W, [cx, cy, cz]);
              for (let i = 0; i < 3; i++) {
                min[i] = Math.min(min[i], q[i]);
                max[i] = Math.max(max[i], q[i]);
              }
            }
      }
    (n.children || []).forEach((c) => walk(c, W));
  };
  j.scenes[j.scene || 0].nodes.forEach((n) => walk(n, [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]));
  out[f.replace('.glb', '')] = { min: min.map(r3), max: max.map(r3) };
}

const body = Object.entries(out)
  .map(([k, v]) => `  ${k}: { min: [${v.min.join(', ')}], max: [${v.max.join(', ')}] },`)
  .join('\n');
writeFileSync(
  new URL('../js/house/models.js', import.meta.url),
  `// GENERATED by tools/build-models.mjs. Do not edit by hand.\n// Bounding boxes of Kenney Furniture Kit models (units: 1 = one 2 m wall width).\nexport const MODELS = {\n${body}\n};\n`,
);
console.log(`models.js written (${Object.keys(out).length} models)`);
